### ISSUE TITLE
[Feature] V11 compatibility

### ISSUE THREAD

**Issue by IHappyEndI** [ortegamarcel/fvtt-gwent#9]
Will there be an update of this wonderful module to version 11?There is a constant problem on the part of the players, they do not see and cannot throw dice on the gwent table.

**Comment by ortegamarcel** [comment]
Yes, there will be. I try to find time this or next week for it.

**Comment by ortegamarcel** [comment]
I just tested it with version v11.305 of Foundry and it worked fine. Can you please try out this version (build 305)? Please let me know if it works or not with that version.

**Comment by IHappyEndI** [comment]
I apologize for the delay in responding. It works fine on version 11.307.
